export const vocab = [
{pl: "głowa", es: "la cabeza", scope: "el-cuerpo"},
{pl: "oko", es: "el ojo", scope: "el-cuerpo"},
{pl: "nos", es: "la nariz", scope: "el-cuerpo"},
{pl: "usta", es: "la boca", scope: "el-cuerpo"},
{pl: "ucho", es: "la oreja", scope: "el-cuerpo"},
{pl: "włosy", es: "el pelo", scope: "el-cuerpo"},
{pl: "twarz", es: "la cara", scope: "el-cuerpo"},
{pl: "ręka (cała)", es: "el brazo", scope: "el-cuerpo"},
{pl: "dłoń", es: "la mano", scope: "el-cuerpo"},
{pl: "palec", es: "el dedo", scope: "el-cuerpo"},
{pl: "noga (cała)", es: "la pierna", scope: "el-cuerpo"},
{pl: "stopa", es: "el pie", scope: "el-cuerpo"},
{pl: "kolano", es: "la rodilla", scope: "el-cuerpo"},
{pl: "brzuch", es: "el estómago", scope: "el-cuerpo"},
{pl: "plecy", es: "la espalda", scope: "el-cuerpo"},
{pl: "ramię", es: "el hombro", scope: "el-cuerpo"},
{pl: "szyja", es: "el cuello", scope: "el-cuerpo"},
{pl: "serce", es: "el corazón", scope: "el-cuerpo"},
{pl: "zęby", es: "los dientes", scope: "el-cuerpo"},
{pl: "język", es: "la lengua", scope: "el-cuerpo"},
{pl: "palec u nogi", es: "el dedo del pie", scope: "el-cuerpo"},
{pl: "ciało", es: "el cuerpo", scope: "el-cuerpo"},
{pl: "skóra", es: "la piel", scope: "el-cuerpo"},
{pl: "broda (zarost)", es: "la barba", scope: "el-cuerpo"},
{pl: "czoło", es: "la frente", scope: "el-cuerpo"},

{pl: "czytać", es: "leer", scope: "ocio-y-tiempo-libre"},
{pl: "oglądać telewizję", es: "ver la televisión", scope: "ocio-y-tiempo-libre"},
{pl: "słuchać muzyki", es: "escuchar música", scope: "ocio-y-tiempo-libre"},
{pl: "grać w piłkę nożną", es: "jugar al fútbol", scope: "ocio-y-tiempo-libre"},
{pl: "grać w gry komputerowe", es: "jugar a los videojuegos", scope: "ocio-y-tiempo-libre"},
{pl: "spacerować", es: "pasear", scope: "ocio-y-tiempo-libre"},
{pl: "tańczyć", es: "bailar", scope: "ocio-y-tiempo-libre"},
{pl: "śpiewać", es: "cantar", scope: "ocio-y-tiempo-libre"},
{pl: "gotować", es: "cocinar", scope: "ocio-y-tiempo-libre"},
{pl: "spotykać się z przyjaciółmi", es: "quedar con amigos", scope: "ocio-y-tiempo-libre"},
{pl: "jeździć na rowerze", es: "montar en bicicleta", scope: "ocio-y-tiempo-libre"},
{pl: "pływać", es: "nadar", scope: "ocio-y-tiempo-libre"},
{pl: "podróżować", es: "viajar", scope: "ocio-y-tiempo-libre"},
{pl: "robić zdjęcia", es: "hacer fotos", scope: "ocio-y-tiempo-libre"},
{pl: "rysować", es: "dibujar", scope: "ocio-y-tiempo-libre"},
{pl: "chodzić do kina", es: "ir al cine", scope: "ocio-y-tiempo-libre"},
{pl: "grać na gitarze", es: "tocar la guitarra", scope: "ocio-y-tiempo-libre"},
{pl: "uprawiać sport", es: "hacer deporte", scope: "ocio-y-tiempo-libre"},
{pl: "czytać książki", es: "leer libros", scope: "ocio-y-tiempo-libre"},
{pl: "surfować po internecie", es: "navegar por internet", scope: "ocio-y-tiempo-libre"},
{pl: "oglądać seriale", es: "ver series", scope: "ocio-y-tiempo-libre"},
{pl: "odpoczywać", es: "descansar", scope: "ocio-y-tiempo-libre"},

{pl: "Jak masz na imię?", es: "¿Cómo te llamas?", scope: "preguntas"},
{pl: "Ile masz lat?", es: "¿Cuántos años tienes?", scope: "preguntas"},
{pl: "Skąd jesteś?", es: "¿De dónde eres?", scope: "preguntas"},
{pl: "Gdzie mieszkasz?", es: "¿Dónde vives?", scope: "preguntas"},
{pl: "Co robisz?", es: "¿Qué haces?", scope: "preguntas"},
{pl: "Co lubisz robić?", es: "¿Qué te gusta hacer?", scope: "preguntas"},
{pl: "Masz rodzeństwo?", es: "¿Tienes hermanos?", scope: "preguntas"},
{pl: "Jaka jest twoja ulubiona potrawa?", es: "¿Cuál es tu comida favorita?", scope: "preguntas"},
{pl: "O której godzinie wstajesz?", es: "¿A qué hora te levantas?", scope: "preguntas"},
{pl: "Mówisz po hiszpańsku?", es: "¿Hablas español?", scope: "preguntas"},
{pl: "Dlaczego uczysz się hiszpańskiego?", es: "¿Por qué estudias español?", scope: "preguntas"},
{pl: "Co robisz w wolnym czasie?", es: "¿Qué haces en tu tiempo libre?", scope: "preguntas"},

{pl: "przystojny", es: "guapo", scope: "ser"},
  {pl: "brzydki", es: "feo", scope: "ser"},
  {pl: "gruby", es: "gordo", scope: "ser"},
  {pl: "szczupły", es: "delgado", scope: "ser"},
  {pl: "blondyn", es: "rubio", scope: "ser"},
  {pl: "ciemnowłosy", es: "moreno", scope: "ser"},
  {pl: "brązowowłosy", es: "castaño", scope: "ser"},
  {pl: "siwy", es: "blanco / gris", scope: "ser"},
  {pl: "farbowany", es: "teñido", scope: "ser"},
  {pl: "wysoki", es: "alto", scope: "ser"},
  {pl: "niski", es: "bajo", scope: "ser"},
  {pl: "silny", es: "fuerte", scope: "ser"},
  {pl: "słaby", es: "débil", scope: "ser"},
  {pl: "stary", es: "viejo", scope: "ser"},
  {pl: "młody", es: "joven", scope: "ser"},
  {pl: "krótkie włosy", es: "corto", scope: "ser"},
  {pl: "długie włosy", es: "largo", scope: "ser"},
  {pl: "proste włosy", es: "liso", scope: "ser"},
  {pl: "kręcone włosy", es: "rizado", scope: "ser"},
  {pl: "falowane włosy", es: "ondulado", scope: "ser"},
  {pl: "łysy", es: "calvo", scope: "ser"},
  {pl: "rudy", es: "pelirrojo", scope: "ser"},
  {pl: "dobry", es: "bueno", scope: "ser"},
  {pl: "zły", es: "malo", scope: "ser"},
  {pl: "sympatyczny", es: "simpático", scope: "ser"},
  {pl: "niesympatyczny", es: "antipático", scope: "ser"},
  {pl: "spokojny", es: "tranquilo", scope: "ser"},
  {pl: "nerwowy", es: "nervioso", scope: "ser"},
  {pl: "introwertyk", es: "introvertido", scope: "ser"},
  {pl: "ekstrawertyk", es: "extrovertido", scope: "ser"},
  {pl: "rozmowny", es: "hablador", scope: "ser"},
  {pl: "małomówny", es: "callado", scope: "ser"},
  {pl: "pracowity", es: "trabajador", scope: "ser"},
  {pl: "leniwy", es: "vago", scope: "ser"},
  {pl: "zabawny", es: "divertido", scope: "ser"},
  {pl: "nudny", es: "aburrido", scope: "ser"},
  {pl: "grzeczny", es: "educado", scope: "ser"},
  {pl: "niegrzeczny", es: "maleducado", scope: "ser"},
  {pl: "głupi", es: "tonto", scope: "ser"},
  {pl: "inteligentny", es: "inteligente", scope: "ser"},
  {pl: "szczery", es: "sincero", scope: "ser"},
  {pl: "kłamliwy", es: "mentiroso", scope: "ser"},
  {pl: "miły", es: "agradable", scope: "ser"},
  {pl: "niemiły", es: "desagradable", scope: "ser"},
  {pl: "hojny", es: "generoso", scope: "ser"},
  {pl: "skąpy", es: "tacaño", scope: "ser"},

  {pl: "ładny uśmiech", es: "una sonrisa bonita", scope: "tener"},
  {pl: "jasne oczy", es: "ojos claros", scope: "tener"},
  {pl: "ciemne oczy", es: "ojos oscuros", scope: "tener"},
  {pl: "niebieskie oczy", es: "ojos azules", scope: "tener"},
  {pl: "zielone oczy", es: "ojos verdes", scope: "tener"},
  {pl: "szare oczy", es: "ojos grises", scope: "tener"},
  {pl: "brązowe oczy", es: "ojos marrones", scope: "tener"},

  {pl: "koszulka", es: "camiseta", scope: "llevar"},
  {pl: "sweter", es: "jersey", scope: "llevar"},
  {pl: "kucyk", es: "coleta", scope: "llevar"},
  {pl: "warkocze", es: "trenzas", scope: "llevar"},
  {pl: "naszyjnik", es: "collar", scope: "llevar"},
  {pl: "kolczyki", es: "pendientes", scope: "llevar"},
  {pl: "wąsy", es: "bigote", scope: "llevar"},
  {pl: "okulary", es: "gafas", scope: "llevar"},
  {pl: "broda", es: "barba", scope: "llevar"}
]